name: Upload Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-upload-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/signaling-server .

      - name: Login and Push Docker Image
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push ${{secrets.DOCKER_USERNAME}}/signaling-server